services:
  24rp15460-php:
    build:
      context: ./  

    container_name: 24rp15460-php
    ports:
      - "8083:80"  # Exposing port 80 inside the container to port 8080 on the host
    volumes:
      - .C:/xampp/htdocs/24RP15460_LOGIN_REGISTER_MODULE:/var/www/html  # Mount the current directory to /var/www/html inside the container
    networks:
      - webnet

networks:
  webnet:
    driver: bridge